---
# file: roles/tomcat/tasks/main.yml

- name: version check
  shell: /usr/local/tomcat/bin/version.sh | grep "Server number" | grep {{ version }}
  register: server_number
  ignore_errors: true

- name: 既存のディレクトリ削除
  file: path=/usr/local/tomcat state=absent 
  when: server_number.rc not in [0]

- name: ダウンロード
  get_url:
    url={{ download_url }}
    dest=/usr/local/src/apache-tomcat-{{ version }}.tar.gz
  when: server_number.rc not in [0]

- name: 解凍
  unarchive: src=/usr/local/src/apache-tomcat-{{ version }}.tar.gz dest=/usr/local/src/ copy=no
  when: server_number.rc not in [0]

- name: tomcat.tar.gz 削除
  file: path=/usr/local/src/apache-tomcat-{{ version }}.tar.gz state=absent 
  when: server_number.rc not in [0]

- name: ディレクトリを移動
  shell: mv /usr/local/src/apache-tomcat-{{ version }} /usr/local/tomcat
  when: server_number.rc not in [0]

- name: create tomcat user
  user: name=tomcat

- name: create conf/tomcat-users.xml
  template: src=conf/tomcat-users.xml.j2 dest=/usr/local/tomcat/conf/tomcat-users.xml

- name: ファイルのオーナー変更
  file: dest=/usr/local/tomcat owner=tomcat group=tomcat recurse=yes

- name: 自動起動ファイルの設定
  template: src=etc/systemd/system/tomcat.service dest=/etc/systemd/system/tomcat.service owner=tomcat mode=755

- name: service,自動起動を有効化
  systemd: name=tomcat state=restarted daemon_reload=yes enabled=yes
  become: yes
