---
# file: roles/zabbix/tasks/main.yml

- name: add Zabbix repo
  yum: name=http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm state=present

- name: install zabbix-server-mysql, zabbix-web-mysql, zabbix-agent, zabbix-web-japanese
  yum: name={{item}} state=latest
  with_items:
    - zabbix-server-mysql
    - zabbix-web-mysql
    - zabbix-agent
    - zabbix-web-japanese

- name: exist check zabbix_server.conf.org
  stat: path=/etc/zabbix/zabbix_server.conf.org
  register: zabbix_server_conf

- name: create db
  shell: zcat `ls /usr/share/doc/zabbix-server-mysql-*/create.sql.gz` | mysql -u{{ db_user }} -p{{ db_password }} {{ db_name }}
  when: not zabbix_server_conf.stat.exists

- name: /etc/zabbix/zabbix_server.conf
  shell: cp /etc/zabbix/zabbix_server.conf /etc/zabbix/zabbix_server.conf.org

- name: /etc/zabbix/zabbix_server.conf
  replace: dest='/etc/zabbix/zabbix_server.conf' regexp='# DBPassword=' replace="DBPassword={{ db_password }}"

- name: /etc/httpd/conf.d/zabbix.conf
  shell: cp /etc/httpd/conf.d/zabbix.conf /etc/httpd/conf.d/zabbix.conf.org

- name: zabbix.conf
  replace: dest='/etc/httpd/conf.d/zabbix.conf' regexp='        \# php_value date.timezone Europe/Riga' replace='        php_value date.timezone Asia/Tokyo'

- name: start zabbix-server and enabled
  service: name=zabbix-server state=started enabled=yes

- name: start zabbix-agent and enabled
  service: name=zabbix-agent state=started enabled=yes

- name: start httpd and enabled
  service: name=httpd state=started enabled=yes
