---
# roles/mysql/tasks/main.yml
- name: install mysql
  yum: name={{item}} state=latest
  with_items:
    - libselinux-python
    - MySQL-python
    - mariadb-server
    - mariadb
- name: start mysql and enabled
  service: name=mysqld state=started enabled=yes
