- name:  レポジトリの登録
  yum:
    name: http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm
    state: present

- name: インストール
  yum:
    name: "{{item}}"
    state: latest
    enablerepo: mysql56-community
    disablerepo: mysql57-community
    state: present
  with_items: 
    - mysql-community-server
    - mysql-community-client
    - mysql-community-common
    - mysql-community-libs
    - mysql-community-libs-compat
    - MySQL-python

- name: 起動
  service: name=mysqld state=started enabled=yes

- name: DBの作成
  mysql_db: name={{db}} state=present

- name: ユーザーの作成
  mysql_user: name={{user}} password={{password}} priv={{db}}.*:ALL state=present
