---
# file: roles/docker/tasks/main.yml

- name: install yum-utils device-mapper-persistent-data lvm2
  yum: name={{item}} state=latest
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: create docker.conf
  copy: src=etc/systemd/system/docker.service.d/docker.conf dest=/etc/systemd/system/docker.service.d/ owner=root mode=0644

- name: add docker repo
  shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
  args:
    chdir: "/etc/yum.repos.d"
    creates: docker-ce.repo

- name: install docker-ce
  yum: name=docker-ce state=latest

- name: start docker and enabled
  service: name=docker state=started enabled=yes

- name: add docker yum repo
  yum_repository:
    name: dockerrepo
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/$releasever/
    enabled: yes
    gpgkey: https://yum.dockerproject.org/gpg
    gpgcheck: yes
  tags: dockerhost

- name: install docker-python
  yum: name=docker-python enablerepo=dockerrepo state=latest
  tags: dockerhost

- name: pull image
  docker_image: name=huit/jenkins-maven
