---
# file: elk.yml

- name: elk Server
  hosts: elk
  become: yes
  roles:
    - nginx
    - java
    - elasticsearch
    - kibana

- name: fluentd
  hosts: elk-l
  become: yes
  roles:
    - fluentd 
