---
# file: om.yum
- name: OM Server
  hosts: om
  become: yes
  vars:
    root_password: root
    db_name: zabbix
    db_user: zabbix
    db_password: zabbix
    server_id: 12
  roles: 
    - common
    #- java
    #- hinemos
    - mysql
    - zabbix
